insert into institution(id, code, name, city) values(1, '123', 'UFAL', 'Arapiraca')
insert into institution(id, code, name, city) values(2, '456', 'UNEAL', 'Arapiraca')
insert into cource(id, code, name) values(1, '321', 'CC')
insert into cource(id, code, name) values(2, '456', 'MAT')
insert into cource(id, code, name) values(3, '789', 'ARQ')
insert into student(id, registration,cpf,name,birthday, institution_id, cource_id) values(1, 'ABC123', 'jfdskfj','Francisco','1998-08-27', 1, 1)
insert into student(id, registration,cpf,name,birthday, institution_id, cource_id) values(2, 'ABCD123', 'sdfsaf','Maria','2000-08-27', 1, 1)
insert into student(id, registration,cpf,name,birthday, institution_id, cource_id) values(3, 'QWE456', 'kjkalhg','Jorge','2000-08-27', 2, 1)
insert into phone(phone) values ('123456789')
insert into phone_student(phone_id, student_id) values(1,1)
insert into phone_student(phone_id, student_id) values(1,2)
insert into subject(code, workload, name, cource_id) values('123',40,'LP2', 1)
insert into subject_student(semester, absence, grade, subject_id, student_id) values(1, 0, 10, 1, 1)
insert into subject_student(semester, absence, grade, subject_id, student_id) values(2, 0, 10, 1, 1)
